server:
  port: 8082

spring:
  application:
    name: loan-service

  datasource:
    url: ${LOAN_DB_URL:jdbc:postgresql://localhost:5433/loandb}
    username: ${LOAN_DB_USERNAME:smartlend}
    password: ${LOAN_DB_PASSWORD:smartlend123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:smartlend}
    password: ${RABBITMQ_PASSWORD:smartlend123}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: ${RABBITMQ_SSL:false}

jwt:
  secret: ${JWT_SECRET:smartlend-super-secret-jwt-key-change-in-prod}

services:
  ai-scoring-url: ${AI_SCORING_URL:http://localhost:8000}
  user-service-url: ${USER_SERVICE_URL:http://localhost:8081}

rabbitmq:
  exchange: smartlend.exchange
  queue:
    loan-events: loan.events.queue
  routing-key:
    loan-approved: loan.approved
    loan-rejected: loan.rejected
    loan-applied: loan.applied
    user-registered: user.registered
    emi-due: loan.emi.due

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
